name: Publish Package to GitHub NPM Registry

on: 
  release: 
    types: published
    
jobs:
    npm-package:
      permissions:
        packages: write
      runs-on: ubuntu-latest
      steps:
        - name: Checkout Repository
          uses: actions/checkout@v4

        - name: install/setup NodeJS
          uses: actions/setup-node@v4
          with:
            node-version: 20.x
            registry-url: 'https://npm.pkg.github.com/'

        - name: install npm dependencies
          run: npm install

        - name: publish npm
          run: npm publish
          env:
              NODE_AUTH_TOKEN: $ {{ secrets.GITHUB_TOKEN }}